# DOCS:
#   https://snyk.io/blog/vs-code-extension-building-auto-cicd-with-github-actions/
#   https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
#   https://github.com/jeff-hykin/better-cpp-syntax

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '.vscodeignore'
      - '**.txt'
      - '**.md'
      - '**.rc'
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        #with:
        #  node-version: 10.x
      #- name: Install dependencies
      #  run: npm install
      #- name: Run headless test (Mocha)
        #uses: GabrielBB/xvfb-action@v1.0
        #with:
        #  run: |
        #    npm test
      - name: Run headless test 1 (Basic)
        run: npm ci
      - name: Run headless test 2 (Validate grammar)
        # Test once the grammar. FIXME: we need SCP code examples!
        run: |
          export CI_NIX_FOLDER="$PWD"
          chmod +x .ci-commands/project/test.sh
          .ci-commands/project/test.sh
        if: runner.os == 'Linux'
