# DOCS:
#   https://snyk.io/blog/vs-code-extension-building-auto-cicd-with-github-actions/
#   https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
#   https://github.com/dustypomerleau/rust-syntax

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '.vscodeignore'
      - '**.txt'
      - '**.md'
      - '**.rc'
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        #with:
        #  node-version: 10.x
      #- name: Run headless test (Mocha)
        #uses: GabrielBB/xvfb-action@v1.0
        #with:
        #  run: |
        #    npm test
      - name: Validate grammar
        # Test once the grammar. FIXME: we need SCP code examples!
        run: |
          npx vscode-tmgrammar-test@0.0.11 -s source.scp -g syntaxes/scp.tmLanguage.json -t "test/**/*.scp"
        if: runner.os == 'Linux'
